apiVersion: v1
kind: Service
metadata:
  name: client-clusterip-svc
spec:
  # type: ClusterIP # Commmented out since k8 defaults to ClusterIP
  selector:
    app: client
  ports:
    - name: client
      protocol: TCP
      port: 4001
      targetPort: 4001
