apiVersion: v1
kind: Service
metadata:
  name: comments-clusterip-svc
spec:
  # type: ClusterIP # Commmented out since k8 defaults to ClusterIP
  selector:
    app: comments
  ports:
    - name: comments
      protocol: TCP
      port: 4001
      targetPort: 4001
