apiVersion: v1
kind: Service
metadata:
  name: moderation-clusterip-svc
spec:
  # type: ClusterIP # Commmented out since k8 defaults to ClusterIP
  selector:
    app: moderation
  ports:
    - name: moderation
      protocol: TCP
      port: 4003
      targetPort: 4003
