apiVersion: v1
kind: Service
metadata:
  name: event-bus-svc
spec:
  # type: ClusterIP # Commmented out since k8 defaults to ClusterIP
  selector:
    app: event-bus
  ports:
    - name: event-bus
      protocol: TCP
      port: 4005
      targetPort: 4005
