apiVersion: v1
kind: Service
metadata:
  name: posts-svc
spec:
  type: NodePort
  selector:
    app: posts
  ports:
    - name: posts
      protocol: TCP
      port: 4000 # source port i.e. the port which should be hit to redirect to target port
      targetPort: 4000 # Actual port our app is listening on
